### ISSUE TITLE
when I ran the command truffle compile, I found the below error.

### ISSUE THREAD

**Issue by dannyng1988** [jajukajulz/foodprint#25]
Dear Sir,
I was trying out your application, but I encounter some difficulties. Could you please take a look at it? Thank you very much.

`Error: ENOENT: no such file or directory, open '.infurakey'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.<anonymous> (/Users/dannyng/Desktop/foodprint/truffle-config.js:24:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Object.require (internal/modules/cjs/helpers.js:74:18)
    at Function.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:161:1)
    at Function.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:150:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile.js:68:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:56:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
Truffle v5.1.46 (core: 5.1.46)
Node v12.13.0
`

**Comment by dannyng1988** [comment]
When I ran Npm install, I also found the error below.

`8 warnings and 7 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dannyng/Desktop/foodprint/node_modules/scrypt
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN foodprint@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 (node_modules/scrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ jimp@0.16.1
`

**Comment by zhendexuebuhui** [comment]
You can comment the following code in truffle-config.js 

// const fs = require('fs');
// const infuraKey = fs.readFileSync(".infurakey").toString().trim();
// const MNEMONIC = fs.readFileSync(".secret").toString().trim();
// const FROMADDRESS = fs.readFileSync(".fromaddress").toString().trim();

// const infuraRinkebyURL = "https://rinkeby.infura.io/v3/"+infuraKey;


// rinkeby: {
    //   provider: function() {
    //     return new HDWalletProvider(MNEMONIC, infuraRinkebyURL,1)
    //   },
    //   network_id: 4,
    //   from: FROMADDRESS, // account from which to deploy
    // }
